### ISSUE TITLE
List of wrong anime metadata (SUMMER)

### ISSUE THREAD

**Issue by nyouness** [victorgveloso/animes-season-addon#1]
Hii , first ty a loot for this amazing addon i made a list of wrong metadata for SUMMER animes , if fixing it possible i will keep helping with lists like this :

- "Suki na Ko ga Megane wo Wasureta / The Girl I Like Forgot Her Glasses"

-"Rurouni Kenshin": "Meiji Kenkaku Romantan (2023) / Rurouni Kenshin (2023)"

-"BLEACH" : your addon is providing only old finished 1-16 seasons , not season 17 "BLEACH: Sennen Kessen-hen - Ketsubetsu-tan"

-"Jitsu wa Ore, Saikyou Deshita? / Am I Actually the Strongest?"

-"Rurouni Kenshin" : same as BLEACH metadata for old seasons 1-3 , not "Rurouni Kenshin: Meiji Kenkaku Romantan (2023)"

Eiyuu Kyoushitsu : this anime is finished airing but addon is showing that anime still didnt start airing until 27 Mar 2024 (torrentio works fine you can watch full anime episodes) 

Uchi no Kaisha no Chiisai Senpai no Hanashi / My Tiny Senpai

STANGE PLANET : this anime is showing wrong metadata original anime is "Fate/strange Fake: Whispers of Dawn"

Kamisama Kiss : this anime is showing wrong metadata original anime is "Hanma Baki Season 2 / Baki Hanma Season 2"

Ookami shoujo to kuro ouji :this anime is showing wrong metadata original anime is "Shiro Seijo to Kuro Bokushi / Saint Cecilia & Pastor Lawrence"

Ascendance of a Bookworm : this anime is showing wrong metadata original anime is "Higeki no Genkyou to Naru Saikyou Gedou Last Boss Joou wa Tami no Tame ni Tsukushimasu. / The Most Heretical Last Boss Queen: From Villainess to Savior"

The Quintessential Quintuplets : this anime should be in FALL section and like BLEACH wrong metadata 1-2 and not season 3 "The Quintessential Quintuplets∽ / Go-toubun no Hanayome∽"

"How a Realist Hero Rebuilt the Kingdom" : this anime is showing wrong metadata original anime is "Genjitsu no Yohane: SUNSHINE in the MIRROR"

"Sound! Euphonium" : wrong metadata original is OVA "Tokubetsu-hen Hibike! Euphonium: Ensemble Contest / Sound! Euphonium: Special Edition ~Ensemble Contest~"

"FLCL" : this anime is showing worng metadata original anime is "FLCL: Grunge"

"Nanatsu no Taizai: Ensa no Edinburgh - Kouhen" : this anime has broken metadata nothing showing

**Comment by victorgveloso** [comment]
> Hii , first ty a loot for this amazing addon i made a list of wrong metadata for SUMMER animes , if fixing it possible i will keep helping with lists like this :

I appreciate your interest in helping. If you are willing to contribute to our database, I am ready to support it. First, let me explain what would really help us keep the database more consistent. 

We need to agree on some consistent formatting for your contribution. The simple format that comes to mind is a CSV file like this:

```
type,season,name,oldID,newID
type,season,name,oldID,newID
type,season,name,oldID,newID
type,season,name,oldID,newID
type,season,name,oldID,newID
```
Where 

- `type` is either `movie` or `series`, 
- `season` has one of the following values:
  1. SPRING
  2. SUMMER
  3. FALL
  4. WINTER
  5. A year in the range [2001,current year)
- `name` is the exact name found in the corresponding file inside quotation marks, e.g., [summer series file](https://github.com/victorgveloso/animes-season-addon/blob/main/catalog/series/latest_anime_seasons/genre%3DSUMMER.json), [fall series file](https://github.com/victorgveloso/animes-season-addon/blob/main/catalog/series/latest_anime_seasons/genre%3DFALL.json), [2001 movie file](https://github.com/victorgveloso/animes-season-addon/blob/main/catalog/movie/archive_anime_seasons/genre%3D2001.json)
- `oldID` is the current, incorrect ID in the file
- `newID` is the id found in the IMDB URL of the content page (search imdb for the title and collect the id from the correct page's URL)

<img width="814" alt="image" src="https://github.com/victorgveloso/animes-season-addon/assets/11022419/54730906-2b70-4d1a-9883-a3eed03cb480">

I list below the newID and oldID of some of the titles you provided with hyperlinks to the corresponding IMDB page and relevant lines in the database file. 

> * "Suki na Ko ga Megane wo Wasureta / The Girl I Like Forgot Her Glasses"

[Expected IMDB id tt28265657](https://www.imdb.com/title/tt28265657)
[Incorrect IMDB id tt0497548](https://github.com/victorgveloso/animes-season-addon/blob/main/catalog/series/latest_anime_seasons/genre%3DSUMMER.json#L48)

CSV format:
```csv
series,SUMMER,"The Girl I Like Forgot Her Glasses",tt0497548,tt28265657
```

> -"BLEACH" : your addon is providing only old finished 1-16 seasons , not season 17 "BLEACH: Sennen Kessen-hen - Ketsubetsu-tan"

[Expected IMDB id tt14986406](https://www.imdb.com/title/tt14986406/)
[Incorrect IMDB id tt0434665](https://github.com/victorgveloso/animes-season-addon/blob/main/catalog/series/latest_anime_seasons/genre%3DSUMMER.json#L41)

CSV format:
```csv
series,SUMMER,"BLEACH: Thousand-Year Blood War - The Separation",tt0434665,tt14986406
```

> -"Jitsu wa Ore, Saikyou Deshita? / Am I Actually the Strongest?"

[Expected IMDB id tt28254867](https://www.imdb.com/title/tt28254867/)
[Incorrect IMDB id tt4689276](https://github.com/victorgveloso/animes-season-addon/blob/main/catalog/series/latest_anime_seasons/genre%3DSUMMER.json#L83)

CSV format:
```csv
series,SUMMER,"Am I Actually the Strongest?",tt4689276,tt28254867
```

> -"Rurouni Kenshin" : same as BLEACH metadata for old seasons 1-3 , not "Rurouni Kenshin: Meiji Kenkaku Romantan (2023)"

[Expected IMDB id tt22249034](https://www.imdb.com/title/tt22249034)
[Incorrect IMDB id tt0182629](https://github.com/victorgveloso/animes-season-addon/blob/main/catalog/series/latest_anime_seasons/genre%3DSUMMER.json#L118)

CSV format:
```csv
series,SUMMER,"Rurouni Kenshin (2023)",tt0182629,tt22249034
```

> Eiyuu Kyoushitsu : this anime is finished airing but addon is showing that anime still didnt start airing until 27 Mar 2024 (torrentio works fine you can watch full anime episodes)

There is nothing I can do about it. That inconsistency does not come from my addon, it is actually in Stremio's official addon (cinemeta). My add-on only collects the animes from the page https://anilist.co/search/anime?year=2023&season=SUMMER and maps it to IMDB id, which cinemeta uses as index.

> Uchi no Kaisha no Chiisai Senpai no Hanashi / My Tiny Senpai

[Expected IMDB id tt27571597](https://www.imdb.com/title/tt27571597)
[Incorrect IMDB id tt0972713](https://github.com/victorgveloso/animes-season-addon/blob/main/catalog/series/latest_anime_seasons/genre%3DSUMMER.json#L146)

CSV format:
```csv
series,SUMMER,"My Tiny Senpai",tt0972713,tt27571597
```

> STRANGE PLANET : this anime is showing wrong metadata original anime is "Fate/strange Fake: Whispers of Dawn"

[Expected IMDB id tt22264336](https://www.imdb.com/title/tt22264336)
[Incorrect IMDB id tt14914464](https://github.com/victorgveloso/animes-season-addon/blob/main/catalog/series/latest_anime_seasons/genre%3DSUMMER.json#L160)

CSV format:
```csv
series,SUMMER,"Fate/strange Fake -Whispers of Dawn-",tt14914464,tt22264336
```

> Kamisama Kiss : this anime is showing wrong metadata original anime is "Hanma Baki Season 2 / Baki Hanma Season 2"

[Expected IMDB id tt13357140](https://www.imdb.com/title/tt13357140)
[Incorrect IMDB id tt2320220](https://github.com/victorgveloso/animes-season-addon/blob/main/catalog/series/latest_anime_seasons/genre%3DSUMMER.json#L195)

CSV format:
```csv
series,SUMMER,"Baki Hanma Season 2",tt2320220,tt13357140
```
> Ookami shoujo to kuro ouji :this anime is showing wrong metadata original anime is "Shiro Seijo to Kuro Bokushi / Saint Cecilia & Pastor Lawrence"

[Expected IMDB id tt22297732](https://www.imdb.com/title/tt22297732)
[Incorrect IMDB id tt3950092](https://github.com/victorgveloso/animes-season-addon/blob/main/catalog/series/latest_anime_seasons/genre%3DSUMMER.json#L209)

CSV format:
```csv
series,SUMMER,"Saint Cecilia & Pastor Lawrence",tt3950092,tt22297732
```

### And so on... I am not making this comment endless :)

> Ascendance of a Bookworm : this anime is showing wrong metadata original anime is "Higeki no Genkyou to Naru Saikyou Gedou Last Boss Joou wa Tami no Tame ni Tsukushimasu. / The Most Heretical Last Boss Queen: From Villainess to Savior"
> 
> The Quintessential Quintuplets : this anime should be in FALL section and like BLEACH wrong metadata 1-2 and not season 3 "The Quintessential Quintuplets∽ / Go-toubun no Hanayome∽"
> 
> "How a Realist Hero Rebuilt the Kingdom" : this anime is showing wrong metadata original anime is "Genjitsu no Yohane: SUNSHINE in the MIRROR"
> 
> "Sound! Euphonium" : wrong metadata original is OVA "Tokubetsu-hen Hibike! Euphonium: Ensemble Contest / Sound! Euphonium: Special Edition ~Ensemble Contest~"
> 
> "FLCL" : this anime is showing worng metadata original anime is "FLCL: Grunge"


> "Nanatsu no Taizai: Ensa no Edinburgh - Kouhen" : this anime has broken metadata nothing showing

[Expected IMDB id tt25010142](https://www.imdb.com/title/tt25010142)
[Correct IMDB id tt25010142](https://github.com/victorgveloso/animes-season-addon/blob/main/catalog/series/latest_anime_seasons/genre%3DSUMMER.json#L349)

It is correct; no need for a CSV entry.

The broken metadata is cinemeta's fault.

----

`Note: this is a hobby project so I do not have much free time to invest in it. In the upcoming weekends, I will implement support for applying patches for changes you report in the CSV file format I mentioned.`

For now, you can create a Pull Request or add a comment to this issue where you maintain the CSV data I described. 

I hope you understand and keep interested in contributing to the project. Feel free to ask further questions you may have.

Merging all the example CSV lines:

```csv
series,SUMMER,"The Girl I Like Forgot Her Glasses",tt0497548,tt28265657
series,SUMMER,"BLEACH: Thousand-Year Blood War - The Separation",tt0434665,tt14986406
series,SUMMER,"Am I Actually the Strongest?",tt4689276,tt28254867
series,SUMMER,"Rurouni Kenshin (2023)",tt0182629,tt22249034
series,SUMMER,"My Tiny Senpai",tt0972713,tt27571597
series,SUMMER,"Fate/strange Fake -Whispers of Dawn-",tt14914464,tt22264336
series,SUMMER,"Baki Hanma Season 2",tt2320220,tt13357140
series,SUMMER,"Saint Cecilia & Pastor Lawrence",tt3950092,tt22297732
```

**Comment by victorgveloso** [comment]
By the way, most of the incorrect cases you found have inconsistent titles between IMDB and anilist. That is where the problem might come from.

**Comment by victorgveloso** [comment]
Actually, I didn't wait until next weekend to implement it.

Commit 8e0dd32 FIXES this issue. In order to contribute, you only need to suggest modifications to the file https://github.com/victorgveloso/animes-season-addon/blob/main/postprocess/fix/catalog/manual.csv look forward to your contribution

**Comment by nyouness** [comment]
Thanks a loot for the explaining and help , sure i would love to help  , now if i understand you correctly i should always do modifications to manual.csv file right ? and how to do that ? , sorry i know just little bit of github i never did a Pull Request or contribute to any project ( simple guide how to do it and i would appreciate  ) .

**Comment by victorgveloso** [comment]
> Thanks a loot for the explaining and help , sure i would love to help , now if i understand you correctly i should always do modifications to manual.csv file right ? 

Exactly

> how to do that ?

See the attached video. I demonstrate how to create your first PR using a third-party github account.

https://github.com/victorgveloso/animes-season-addon/assets/11022419/7b52c25e-b2a3-47d7-9e8c-3078e5b3b127

**Comment by victorgveloso** [comment]
Hi @nyouness, I would like to make one last comment about your contribution. 

You may have noticed that your changes did not take effect in the plugin. The reason is an issue I have just noticed: Despite being valid and correctly formatted titles, you used different names for the animes rather than the ones used in my [catalog](https://github.com/victorgveloso/animes-season-addon/tree/main/catalog). Sometimes the anime titles in my [catalog](https://github.com/victorgveloso/animes-season-addon/tree/main/catalog) are in Romaji or contain "Season X".

For future contributions, could you try to copy the exact name of the anime as it appears in the [catalog](https://github.com/victorgveloso/animes-season-addon/tree/main/catalog)? 

I fixed the names in the commit e9f69a6dac700c18c117d35064446b74d0fd8e11.

Unrelated but still relevant for future contributions; I added support for quoted and unquoted titles (450fa5738b669b3bc14f053339065981b7e1c12a). From now on, try to avoid quotation marks unless the anime title contains at least one "," ( comma ). That is why I removed the quotation marks from your input (ea4a050dc109b08c9bfd37019d0a04c64a3ced35).  This is not mandatory but is a nice cosmetic practice that will help keep the `manual.csv` file clean.

**Comment by nyouness** [comment]
Ohh yep i have noticed that , sure , i will make sure that i put correct titles from your catalog and avoid quotation marks unless the anime title contains it .

**Comment by TheAymen** [comment]
I like this add-on because it does what it says on the tin well. I just wish there was some way to have compatibility with Animeo add-on AniList tracking when it's set to "Kitsu only".
