### ISSUE TITLE
Anichart

### ISSUE THREAD

**Issue by trancephormer** [victorgveloso/animes-season-addon#13]
Is it not possible to get the weekly dates/info etc from anichart/mal/ANN etc instead of Imdb
Imdb really doesn't update as well as well as them, coz nobody bothers to edit anime stuff there. 
I don't know jack about coding and API  (or if you're already getting it from those places instead) etc so just curious. Thanks for making this add-on btw

Also idk if it's designed this way, but the description for anime (using Loner life as an example here) on the main catalog screen is from muse/anime websites and when you click on it then it switches to IMDb. For loner it doesn't show the dates etc on pc but shows them on mobile.  
![IMG_20240929_145158945_HDR](https://github.com/user-attachments/assets/bc5a29a1-766d-40f2-aef8-ad90acf6fb57)
![IMG_20240929_145240158_HDR](https://github.com/user-attachments/assets/a59adbd4-e29d-4530-b02d-7c066e5be602)
![Screenshot_20240929-145522_Stremio](https://github.com/user-attachments/assets/3b19f553-410e-4bc8-afcd-9f64041d4915)

**Comment by victorgveloso** [comment]
Hi @trancephormer , thanks for the interest in our add-on. 

> Is it not possible to get the weekly dates/info etc from anichart/mal/ANN etc instead of Imdb
 
This is a catalog add-on, metadata is a meta add-on responsibility, and stremio has an official meta add-on that relies on IMDb id. Being official means it has compatibility with all add-ons. We could create separate catalog add-on versions. Each supporting one unofficial meta add-on (kitsu or TMDb) but they might have fewer download options as support from stream add-ons is not guaranteed. Developing an anilist meta add-on is even worse as no stream add-on supports it yet.

> Imdb really doesn't update as well as well as them, coz nobody bothers to edit anime stuff there.

That's the entire point of this add-on. We know IMDb can be messy when it comes to tracking animes but as long as it's the main ID used by stream add-ons to index content, we put effort in mapping IMDb to anilist id so we can take advantage of both worlds. 

I would say most of the IMDb problems vanish by the time the animes' episodes start airing. 

> Also idk if it's designed this way, but the description for anime (using Loner life as an example here) on the main catalog screen is from muse/anime websites and when you click on it then it switches to IMDb. 

While catalog add-ons provide basic metadata, the stremio PC client only shows it as a placeholder until cinemeta's metadata is ready/loaded.  

> For loner it doesn't show the dates etc on pc but shows them on mobile.

Unlike the PC version, the mobile app never shows metadata from the catalog. It defaults to cinemeta's. So it's true that some informations might be different according to your platform.

So this add-on basically converts anilist id to IMDb id while leveraging the public API of anime seasons from anichart. There's another community add-on that provides anilist catalog with anilist meta, it was the main inspiration for this add-on. It doesn't have as much download links and subtitle options as ours.

**Comment by trancephormer** [comment]
I understand, appreciate you maintaining this and for the detailed insights into my dumb queries. its quite priceless and i use it daily, thanks again, cheers.

**Comment by trancephormer** [comment]
Do you have any idea why some anime doesn't show up in the calendar despite having dates show up when you click on the the UI metadata (like the notorious talker one rn). 

Also just curious about other add-ons too like the doing a search and getting results from normal catalogue one, and kitsu etc they will have the airing dates but it won't show up in the calendar, so just curious if there's some reason/fix in general.
